version: '3'

services:
  mysql:
    container_name: bamdoliro_stupetition_mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "bamdoliro"
      MYSQL_PASSWORD: "bamdoliro"
      MYSQL_DATABASE: "bamdoliro_stupetition"
    ports:
      - "3308:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  redis:
    image: redis:latest
    container_name: bamdoliro_stupetition_redis
    hostname: bamdoliro
    command: redis-server --port 6379
    ports:
      - "6379:6379"