version: '3'

services:
  mysql:
    container_name: ${DB_NAME}
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  redis:
    image: redis:7.0-alpine
    container_name: bamdoliro_stupetition_redis
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    env_file:
      - .env
    ports:
      - 6379:6379

  application:
    build:
      context: .
      dockerfile: Dockerfile.dev
    expose:
      - 8080
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql
    environment:
      - TZ="Asia/Seoul"