version: '3'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Seoul
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3306:3306
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  redis:
    image: redis:7.0-alpine
    container_name: bamdoliro_stupetition_redis
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379

  application:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}
    expose:
      - 8080
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    environment:
      - TZ="Asia/Seoul"

volumes:
  mysql-volume: { }