spring:
  profiles:
    active: local

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

    generate-ddl: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  redis:
    port: 6379

  cache:
    type: redis

  jwt:
    secret: ${JWT_SECRET}

auth:
  google:
    base-url: ${GOOGLE_BASE_URL}
    client-id: ${GOOGLE_CLIENT}
    client-secret: ${GOOGLE_SECRET}
    redirect-url: ${GOOGLE_REDIRECT}

---
spring:
  config:
    activate:
      on-profile: dev

  redis:
    host: redis
    password: ${REDIS_PASSWORD}

debug: true
---
spring:
  config:
    activate:
      on-profile: prod

  redis:
    host: redis
    password: ${REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3308/bamdoliro_stupetition
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bamdoliro
    password: bamdoliro

  redis:
    host: localhost
    password: bamdoliro

debug: true