spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://127.0.0.1:3308/bamdoliro_stupetition
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bamdoliro
    password: bamdoliro

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  jwt:
    secret: asdfasdfasdfasfasdfadsfadsfasdfsadfsdfasfsfasdfsafasdfasdfasfasfasdsafsdffadsfasdfasfasf

  cache:
    type: redis

  redis:
    host: localhost
    port: 6379

debug: true
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://mysql:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  jwt:
    secret: ${JWT_SECRET}

  cache:
    type: redis

  redis:
    host: redis
    port: 6379

debug: true
---
spring:
  config:
    activate:
      on-profile: product

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    generate-ddl: false